export const RENDER_AUTH_VALUE = 'RENDER_AUTH_VALUE';
export const RENDER_INITIAL_AUTH = 'RENDER_INITIAL_AUTH'

//cars
export const GET_ALL_CARS_SUCCESS = 'GET_ALL_CARS_SUCCESS'

//parts
export const GET_ALL_PARTS_SUCCESS = 'GET_ALL_PARTS_SUCCESS'